### ISSUE TITLE
Docker build fails.

### ISSUE THREAD

**Issue by TomMiksa** [IrinaAvram/DMPGenerator#1]
I am trying to run the docker container, but I am getting the following error:

docker build -f docker/frontend.Dockerfile -t frontend .

Sending build context to Docker daemon  4.756MB
Step 1/6 : FROM agileek/ionic-framework:latest
 ---> 851f7bf60dc5
Step 2/6 : ADD Frontend /app
 ---> Using cache
 ---> 040743380b08
Step 3/6 : WORKDIR /app
 ---> Using cache
 ---> 24843907ff01
Step 4/6 : RUN npm install
 ---> Running in a92813efc556
npm ERR! code ENOLOCAL
npm ERR! Could not install from "bower_components/public-license-selector" as it does not contain a package.json file.

Can you please investigate this?

P.S. The backend builds without problems.

**Comment by IrinaAvram** [comment]
At some point during development we tried using bower for the license selector but that has been subsequently removed and a residual dependency has been left in the project by mistake. 

The issue has now been solved through the referenced commit.
